# Generated by Django 4.2.5 on 2023-11-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yacht_app', '0002_comment_uploaded_file_comment_uploaded_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='yacht_app.company'),
        ),
    ]
