# Generated by Django 4.2.5 on 2023-11-01 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yacht_app', '0003_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='yacht',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='yacht',
            name='draft',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='length',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='yacht',
            name='year_built',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yacht_app.company'),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='company',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='yacht',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
